import re
from typing import Dict, Any, Tuple
from datetime import datetime

class ResponseParser:
    """
    Parses the raw text output from the LLM (which follows a strict prompt template)
    into structured 'answer_with_explanation' field.
    """

    def parse_llm_output(self, raw_text: str) -> Dict[str, str]:
        """
        Attempts to parse the raw text output based on the expected format:
        "Answer with Explanation: [content]."

        Args:
            raw_text: The full text generated by the LLM.

        Returns:
            A dictionary containing 'answer_with_explanation'.
        """
        
        # 1. Clean up and standardize spacing
        text = raw_text.strip().replace('\n', ' ')
        
        # Handle cases where the model might generate a double 'Answer with Explanation:' 
        text = re.sub(r'Answer with Explanation:\s*Answer with Explanation:', 'Answer with Explanation:', text, flags=re.IGNORECASE)

        # 2. Use Regex to extract content after "Answer with Explanation:"
        match = re.search(
            r'Answer with Explanation:\s*(.*)', 
            text, 
            re.IGNORECASE | re.DOTALL
        )

        if match:
            answer_with_explanation = match.group(1).strip()
        else:
            # Fallback: If parsing fails, use the raw text
            answer_with_explanation = text
                
        return {
            "answer_with_explanation": answer_with_explanation
        }